# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\x0fminisql.gateway\"\x1d\n\x0e\x45xecuteRequest\x12\x0b\n\x03sql\x18\x01 \x01(\t\"\xb7\x01\n\x0f\x45xecuteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nerror_code\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12/\n\x06update\x18\n \x01(\x0b\x32\x1d.minisql.gateway.UpdateResultH\x00\x12-\n\x05query\x18\x0b \x01(\x0b\x32\x1c.minisql.gateway.QueryResultH\x00\x42\x08\n\x06result\"%\n\x0cUpdateResult\x12\x15\n\raffected_rows\x18\x01 \x01(\x05\"B\n\x0bQueryResult\x12\x0f\n\x07\x63olumns\x18\x01 \x03(\t\x12\"\n\x04rows\x18\x02 \x03(\x0b\x32\x14.minisql.gateway.Row\"2\n\x03Row\x12+\n\x06values\x18\x01 \x03(\x0b\x32\x1b.minisql.gateway.TypedValue\"\xa2\x01\n\nTypedValue\x12\x30\n\nnull_value\x18\x01 \x01(\x0e\x32\x1a.minisql.gateway.NullValueH\x00\x12\x13\n\tint_value\x18\x02 \x01(\x03H\x00\x12\x16\n\x0c\x64ouble_value\x18\x03 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x04 \x01(\tH\x00\x12\x14\n\nbool_value\x18\x05 \x01(\x08H\x00\x42\x07\n\x05value\"\r\n\x0bPingRequest\"7\n\x0cPingResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x16\n\x0eserver_time_ms\x18\x02 \x01(\x03*\x1b\n\tNullValue\x12\x0e\n\nNULL_VALUE\x10\x00\x32\xa3\x01\n\x0eGatewayService\x12L\n\x07\x45xecute\x12\x1f.minisql.gateway.ExecuteRequest\x1a .minisql.gateway.ExecuteResponse\x12\x43\n\x04Ping\x12\x1c.minisql.gateway.PingRequest\x1a\x1d.minisql.gateway.PingResponseB2\n com.minisql.client.gateway.protoB\x0cGatewayProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.minisql.client.gateway.protoB\014GatewayProtoP\001'
  _globals['_NULLVALUE']._serialized_start=647
  _globals['_NULLVALUE']._serialized_end=674
  _globals['_EXECUTEREQUEST']._serialized_start=34
  _globals['_EXECUTEREQUEST']._serialized_end=63
  _globals['_EXECUTERESPONSE']._serialized_start=66
  _globals['_EXECUTERESPONSE']._serialized_end=249
  _globals['_UPDATERESULT']._serialized_start=251
  _globals['_UPDATERESULT']._serialized_end=288
  _globals['_QUERYRESULT']._serialized_start=290
  _globals['_QUERYRESULT']._serialized_end=356
  _globals['_ROW']._serialized_start=358
  _globals['_ROW']._serialized_end=408
  _globals['_TYPEDVALUE']._serialized_start=411
  _globals['_TYPEDVALUE']._serialized_end=573
  _globals['_PINGREQUEST']._serialized_start=575
  _globals['_PINGREQUEST']._serialized_end=588
  _globals['_PINGRESPONSE']._serialized_start=590
  _globals['_PINGRESPONSE']._serialized_end=645
  _globals['_GATEWAYSERVICE']._serialized_start=677
  _globals['_GATEWAYSERVICE']._serialized_end=840
# @@protoc_insertion_point(module_scope)
